global:
  scrape_interval: 5s

scrape_configs:
  - job_name: product-api-job
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ host.docker.internal:8801 ]
        labels:
          application: product-api
